package SensorLanguage.sandbox;

/*Generated by MPS */


public class map_App {
  public static void main(String[] args) {

    System.out.println("#!/bin/bash");


    System.out.println("file1" + "=" + "\"" + "/home/user/Bureau/testShel/exemple.csv" + "\"");
    System.out.println("# Set \",\" as the field separator using $IFS");
    System.out.println("# and read line by line using while read combo");
    System.out.println("while IFS=',' read -r f1 f2 f3 f4 f5 f6 f7");
    System.out.println("do");
    System.out.println("  sensor=$f" + 1 + ";");
    System.out.println("  value=$f" + 3 + ";");
    System.out.println("  time=$f" + 2 + ";");
    System.out.println("  curl -i -XPOST 'http://localhost:8086/write?db=my_database' \\");
    System.out.println("                   --data-binary \"$sensor value=$value $time\";");
    System.out.println("done < \"$" + "file1" + "\"");
    System.out.println("#!/bin/bash");
    System.out.println("function readJson { ");
    System.out.println("      UNAMESTR=`uname`");
    System.out.println("      if [[ '$UNAMESTR' == 'Linux' ]]; then");
    System.out.println("          SED_EXTENDED='-r'");
    System.out.println("      elif [[ '$UNAMESTR' == 'Darwin' ]]; then");
    System.out.println("          SED_EXTENDED='-E'");
    System.out.println("      fi;\n");
    System.out.println("      VALUE=`grep -m 1 \"\"${2}\"\" ${1} | sed ${SED_EXTENDED} 's/^ *//;s/.*: *\"//;s/\",?//'`");
    System.out.println("      if [ ! '$VALUE' ]; then");
    System.out.println("          echo 'Error: Cannot find \'${2}\' in ${1}' >&2;");
    System.out.println("          exit 1;");
    System.out.println("      else");
    System.out.println("          echo $VALUE ;");
    System.out.println("      fi;\n");
    System.out.println("}\n");
    System.out.println("Sensor=`readJson " + "example.json" + "       sensor` || exit 1;");
    System.out.println("Time=`readJson   " + "example.json" + "       time`   || exit 1;");
    System.out.println("Value=`readJson  " + "example.json" + "       value ` || exit 1;");
    System.out.println("echo $Sensor     \necho $Time     \necho $Value");
    System.out.println("curl -i -XPOST 'http://localhost:8086/write?db=my_database' --data-binary 'sensor=$Sensor value=$Value time=$Time';\n");
  }
}
