package SensorLanguage.sandbox;

/*Generated by MPS */


public class map_App {
  public static void main(String[] args) {

    System.out.println("#!/bin/bash");

    System.out.println("file1" + "=" + "\"" + "/home/user/Bureau/testShel/exemple.csv" + "\"");
    System.out.println("# Set \",\" as the field separator using $IFS");
    System.out.println("# and read line by line using while read combo");
    System.out.println("while IFS=',' read -r f1 f2 f3 f4 f5 f6 f7");
    System.out.println("do");
    System.out.println(" echo \"$f1 $f2 $f3 $f4 $f5 $f6 $f7 \"  ");
    System.out.println("done < \"$" + "file1" + "\"");
    System.out.println("file2" + "=" + "\"" + "/home/user/Bureau/testShel/exemple2.csv" + "\"");
    System.out.println("# Set \",\" as the field separator using $IFS");
    System.out.println("# and read line by line using while read combo");
    System.out.println("while IFS=',' read -r f1 f2 f3 f4 f5 f6 f7");
    System.out.println("do");
    System.out.println(" echo \"$f1 $f2 $f3 $f4 $f5 $f6 $f7 \"  ");
    System.out.println("done < \"$" + "file2" + "\"");
  }
}
