package SensorLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int App = 0;
  public static final int FileCsv = 1;
  public static final int FileJson = 2;
  public static final int Replay = 3;
  public static final int sensor = 4;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x976c57d85cc4413L, 0xa01a155ebd2f878fL);
    builder.put(0x7339e17e1917cdb0L, App);
    builder.put(0x7339e17e19250f70L, FileCsv);
    builder.put(0x7339e17e19251020L, FileJson);
    builder.put(0x7339e17e1919e069L, Replay);
    builder.put(0x7339e17e1919e158L, sensor);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
