package SensorLanguage.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum RisqueGorilla {
  low("low", "low"),
  average("average", "average"),
  strong("strong", "stong");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private RisqueGorilla(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<RisqueGorilla> getConstants() {
    List<RisqueGorilla> list = ListSequence.fromList(new LinkedList<RisqueGorilla>());
    ListSequence.fromList(list).addElement(RisqueGorilla.low);
    ListSequence.fromList(list).addElement(RisqueGorilla.average);
    ListSequence.fromList(list).addElement(RisqueGorilla.strong);
    return list;
  }
  public static RisqueGorilla getDefault() {
    return RisqueGorilla.low;
  }
  public static RisqueGorilla parseValue(String value) {
    if (value == null) {
      return RisqueGorilla.getDefault();
    }
    if (value.equals(RisqueGorilla.low.getValueAsString())) {
      return RisqueGorilla.low;
    }
    if (value.equals(RisqueGorilla.average.getValueAsString())) {
      return RisqueGorilla.average;
    }
    if (value.equals(RisqueGorilla.strong.getValueAsString())) {
      return RisqueGorilla.strong;
    }
    return RisqueGorilla.getDefault();
  }
}
