package SensorLanguage.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum RisqueChaos {
  low("low", "low"),
  average("average", "average"),
  strong("strong", "strong");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private RisqueChaos(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<RisqueChaos> getConstants() {
    List<RisqueChaos> list = ListSequence.fromList(new LinkedList<RisqueChaos>());
    ListSequence.fromList(list).addElement(RisqueChaos.low);
    ListSequence.fromList(list).addElement(RisqueChaos.average);
    ListSequence.fromList(list).addElement(RisqueChaos.strong);
    return list;
  }
  public static RisqueChaos getDefault() {
    return RisqueChaos.low;
  }
  public static RisqueChaos parseValue(String value) {
    if (value == null) {
      return RisqueChaos.getDefault();
    }
    if (value.equals(RisqueChaos.low.getValueAsString())) {
      return RisqueChaos.low;
    }
    if (value.equals(RisqueChaos.average.getValueAsString())) {
      return RisqueChaos.average;
    }
    if (value.equals(RisqueChaos.strong.getValueAsString())) {
      return RisqueChaos.strong;
    }
    return RisqueChaos.getDefault();
  }
}
