package SensorLanguage.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum TypeLow {
  random("random", "random"),
  markov("markov", "markov"),
  file("file", "file"),
  function("function", "function");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private TypeLow(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<TypeLow> getConstants() {
    List<TypeLow> list = ListSequence.fromList(new LinkedList<TypeLow>());
    ListSequence.fromList(list).addElement(TypeLow.random);
    ListSequence.fromList(list).addElement(TypeLow.markov);
    ListSequence.fromList(list).addElement(TypeLow.file);
    ListSequence.fromList(list).addElement(TypeLow.function);
    return list;
  }
  public static TypeLow getDefault() {
    return TypeLow.random;
  }
  public static TypeLow parseValue(String value) {
    if (value == null) {
      return TypeLow.getDefault();
    }
    if (value.equals(TypeLow.random.getValueAsString())) {
      return TypeLow.random;
    }
    if (value.equals(TypeLow.markov.getValueAsString())) {
      return TypeLow.markov;
    }
    if (value.equals(TypeLow.file.getValueAsString())) {
      return TypeLow.file;
    }
    if (value.equals(TypeLow.function.getValueAsString())) {
      return TypeLow.function;
    }
    return TypeLow.getDefault();
  }
}
