package SensorLanguage.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum TYPE {
  CSV("CSV", "csv"),
  JSON("JSON", "json"),
  SQL("SQL", "sql");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private TYPE(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<TYPE> getConstants() {
    List<TYPE> list = ListSequence.fromList(new LinkedList<TYPE>());
    ListSequence.fromList(list).addElement(TYPE.CSV);
    ListSequence.fromList(list).addElement(TYPE.JSON);
    ListSequence.fromList(list).addElement(TYPE.SQL);
    return list;
  }
  public static TYPE getDefault() {
    return TYPE.CSV;
  }
  public static TYPE parseValue(String value) {
    if (value == null) {
      return TYPE.getDefault();
    }
    if (value.equals(TYPE.CSV.getValueAsString())) {
      return TYPE.CSV;
    }
    if (value.equals(TYPE.JSON.getValueAsString())) {
      return TYPE.JSON;
    }
    if (value.equals(TYPE.SQL.getValueAsString())) {
      return TYPE.SQL;
    }
    return TYPE.getDefault();
  }
}
