package SensorLanguage.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum TypeData {
  csv("csv", "csv"),
  json("json", "json");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private TypeData(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<TypeData> getConstants() {
    List<TypeData> list = ListSequence.fromList(new LinkedList<TypeData>());
    ListSequence.fromList(list).addElement(TypeData.csv);
    ListSequence.fromList(list).addElement(TypeData.json);
    return list;
  }
  public static TypeData getDefault() {
    return TypeData.csv;
  }
  public static TypeData parseValue(String value) {
    if (value == null) {
      return TypeData.getDefault();
    }
    if (value.equals(TypeData.csv.getValueAsString())) {
      return TypeData.csv;
    }
    if (value.equals(TypeData.json.getValueAsString())) {
      return TypeData.json;
    }
    return TypeData.getDefault();
  }
}
