package SensorLanguage.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum VALUE {
  _INT(" INT", "int"),
  _BOOLEAN(" BOOLEAN", "boolean"),
  STRING("STRING", "string");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private VALUE(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<VALUE> getConstants() {
    List<VALUE> list = ListSequence.fromList(new LinkedList<VALUE>());
    ListSequence.fromList(list).addElement(VALUE._INT);
    ListSequence.fromList(list).addElement(VALUE._BOOLEAN);
    ListSequence.fromList(list).addElement(VALUE.STRING);
    return list;
  }
  public static VALUE getDefault() {
    return VALUE._INT;
  }
  public static VALUE parseValue(String value) {
    if (value == null) {
      return VALUE.getDefault();
    }
    if (value.equals(VALUE._INT.getValueAsString())) {
      return VALUE._INT;
    }
    if (value.equals(VALUE._BOOLEAN.getValueAsString())) {
      return VALUE._BOOLEAN;
    }
    if (value.equals(VALUE.STRING.getValueAsString())) {
      return VALUE.STRING;
    }
    return VALUE.getDefault();
  }
}
